name: incremental_dom_bindings
description: Dart bindings for the Incremental DOM library. Incremental DOM is a library for expressing and applying updates to DOM trees incrementally.
version: 2.0.0+1
homepage: https://www.github.com/blimster/incremental_dom_bindings

environment:
    sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
    build_runner: ^1.10.0
    build_web_compilers: ^2.7.0
    pedantic: ^1.10.0
    test: ^1.16.0
