name: incremental_dom_bindings
description: Dart bindings for the Incremental DOM library.
version: 1.0.0
homepage: http://www.github.com/blimster/incremental_dom_bindings

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
    build_runner: ^1.7.0
    build_web_compilers: ^2.7.0
    pedantic: ^1.9.0
    test: ^1.11.0